[package]
name = "theterminal"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { workspace = true }
smol = { workspace = true }
smol-macros = { workspace = true }
contemporary = { workspace = true }
cntp_i18n = { workspace = true }
cntp_icon_tool_macros = { workspace = true }
portable-pty = { workspace = true }
tracing = { workspace = true }
async-channel = { workspace = true }
vt100 = { workspace = true }
ini = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
url = "2.5.7"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-open-directory = { workspace = true }
objc2-foundation = { workspace = true }

[build-dependencies]
cntp_i18n_gen = { workspace = true }