#ifndef LIBTHETERMINALCOMMONEXPORTS_H
#define LIBTHETERMINALCOMMONEXPORTS_H

#ifdef LIBTHETERMINAL_COMMON_LIBRARY
    #define LIBTHETERMINAL_COMMON_EXPORT Q_DECL_EXPORT
#else
    #define LIBTHETERMINAL_COMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBTHETERMINALCOMMONEXPORTS_H
