#ifndef LIBTHETERMINAL_GLOBAL_H
#define LIBTHETERMINAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBTHETERMINAL_LIBRARY)
    #define LIBTHETERMINAL_EXPORT Q_DECL_EXPORT
#else
    #define LIBTHETERMINAL_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBTHETERMINAL_GLOBAL_H
